# Site settings
title: May.Craft.Native.
subtitle: Cвадебный блог.
email: migs1488@gmail.com
description: Наш свадебный блог.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Миша и Надя
street_address:
city: Moscow
state:
zip_code:
country: Russia
phone: +7 (915) 490-98-41

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 15

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/migs911
gitlab_url:
googleplus_url: https://plus.google.com/+MishaGoncharov
instagram_url:
linkedin_url: https://www.linkedin.com/in/misha-goncharov-35285987/
pinterest_url:
slack_url:
twitter_url:
vk_url: https://vk.com/id286624

# Build settings
markdown: kramdown

sass:
  style: compressed
